site_name: Elegy
repo_name: poets-ai/elegy
repo_url: https://github.com/poets-ai/elegy
site_url: https://poets-ai.github.io/elegy
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16
nav:
- Introduction: index.md
- Getting Started: getting-started.ipynb
- Guides:
    The Module System: guides/module-system.md
    Modules, Losses, and Metrics: guides/modules-losses-metrics.md
    Contributing: guides/contributing.md
- API Reference:
    GeneralizedModule: api/GeneralizedModule.md
    GeneralizedOptimizer: api/GeneralizedOptimizer.md
    GradStep: api/GradStep.md
    HaikuModule: api/HaikuModule.md
    Loss: api/Loss.md
    Losses: api/Losses.md
    Metric: api/Metric.md
    Metrics: api/Metrics.md
    Model: api/Model.md
    ModelBase: api/ModelBase.md
    Module: api/Module.md
    Optimizer: api/Optimizer.md
    OutputStates: api/OutputStates.md
    PredStep: api/PredStep.md
    RNGSeq: api/RNGSeq.md
    States: api/States.md
    TestStep: api/TestStep.md
    TrainStep: api/TrainStep.md
    Uninitialized: api/Uninitialized.md
    add_loss: api/add_loss.md
    add_metric: api/add_metric.md
    add_summary: api/add_summary.md
    callbacks:
      CSVLogger: api/callbacks/CSVLogger.md
      Callback: api/callbacks/Callback.md
      CallbackList: api/callbacks/CallbackList.md
      EarlyStopping: api/callbacks/EarlyStopping.md
      History: api/callbacks/History.md
      LambdaCallback: api/callbacks/LambdaCallback.md
      ModelCheckpoint: api/callbacks/ModelCheckpoint.md
      RemoteMonitor: api/callbacks/RemoteMonitor.md
      TensorBoard: api/callbacks/TensorBoard.md
      TerminateOnNaN: api/callbacks/TerminateOnNaN.md
    context: api/context.md
    flax_summarize: api/flax_summarize.md
    flax_summary: api/flax_summary.md
    get_losses: api/get_losses.md
    get_metrics: api/get_metrics.md
    get_summaries: api/get_summaries.md
    initializers:
      Constant: api/initializers/Constant.md
      Orthogonal: api/initializers/Orthogonal.md
      RandomNormal: api/initializers/RandomNormal.md
      RandomUniform: api/initializers/RandomUniform.md
      TruncatedNormal: api/initializers/TruncatedNormal.md
      UniformScaling: api/initializers/UniformScaling.md
      VarianceScaling: api/initializers/VarianceScaling.md
    inject_dependencies: api/inject_dependencies.md
    jit: api/jit.md
    losses:
      BinaryCrossentropy: api/losses/BinaryCrossentropy.md
      CategoricalCrossentropy: api/losses/CategoricalCrossentropy.md
      CosineSimilarity: api/losses/CosineSimilarity.md
      Huber: api/losses/Huber.md
      Loss: api/losses/Loss.md
      MeanAbsoluteError: api/losses/MeanAbsoluteError.md
      MeanAbsolutePercentageError: api/losses/MeanAbsolutePercentageError.md
      MeanSquaredError: api/losses/MeanSquaredError.md
      MeanSquaredLogarithmicError: api/losses/MeanSquaredLogarithmicError.md
      Reduction: api/losses/Reduction.md
      SparseCategoricalCrossentropy: api/losses/SparseCategoricalCrossentropy.md
      binary_crossentropy: api/losses/binary_crossentropy.md
      cosine_similarity: api/losses/cosine_similarity.md
      huber: api/losses/huber.md
      mean_absolute_error: api/losses/mean_absolute_error.md
      mean_absolute_percentage_error: api/losses/mean_absolute_percentage_error.md
      mean_squared_error: api/losses/mean_squared_error.md
      mean_squared_logarithmic_error: api/losses/mean_squared_logarithmic_error.md
      sparse_categorical_crossentropy: api/losses/sparse_categorical_crossentropy.md
    metrics:
      Accuracy: api/metrics/Accuracy.md
      BinaryAccuracy: api/metrics/BinaryAccuracy.md
      BinaryCrossentropy: api/metrics/BinaryCrossentropy.md
      CategoricalAccuracy: api/metrics/CategoricalAccuracy.md
      F1: api/metrics/F1.md
      Mean: api/metrics/Mean.md
      MeanAbsoluteError: api/metrics/MeanAbsoluteError.md
      MeanAbsolutePercentageError: api/metrics/MeanAbsolutePercentageError.md
      MeanSquaredError: api/metrics/MeanSquaredError.md
      Metric: api/metrics/Metric.md
      Precision: api/metrics/Precision.md
      Recall: api/metrics/Recall.md
      Reduce: api/metrics/Reduce.md
      Reduction: api/metrics/Reduction.md
      SparseCategoricalAccuracy: api/metrics/SparseCategoricalAccuracy.md
      Sum: api/metrics/Sum.md
      accuracy: api/metrics/accuracy.md
      binary_accuracy: api/metrics/binary_accuracy.md
      binary_crossentropy: api/metrics/binary_crossentropy.md
      categorical_accuracy: api/metrics/categorical_accuracy.md
      f1: api/metrics/f1.md
      mean_absolute_error: api/metrics/mean_absolute_error.md
      mean_absolute_percentage_error: api/metrics/mean_absolute_percentage_error.md
      mean_squared_error: api/metrics/mean_squared_error.md
      precision: api/metrics/precision.md
      recall: api/metrics/recall.md
      reduce: api/metrics/reduce.md
      sparse_categorical_accuracy: api/metrics/sparse_categorical_accuracy.md
    nets:
      ResNet: api/nets/ResNet.md
      ResNet101: api/nets/ResNet101.md
      ResNet152: api/nets/ResNet152.md
      ResNet18: api/nets/ResNet18.md
      ResNet200: api/nets/ResNet200.md
      ResNet34: api/nets/ResNet34.md
      ResNet50: api/nets/ResNet50.md
    nn:
      AvgPool: api/nn/AvgPool.md
      BatchNormalization: api/nn/BatchNormalization.md
      Conv1D: api/nn/Conv1D.md
      Conv2D: api/nn/Conv2D.md
      Conv3D: api/nn/Conv3D.md
      ConvND: api/nn/ConvND.md
      Dropout: api/nn/Dropout.md
      EmbedLookupStyle: api/nn/EmbedLookupStyle.md
      Embedding: api/nn/Embedding.md
      Flatten: api/nn/Flatten.md
      InstanceNormalization: api/nn/InstanceNormalization.md
      LayerNormalization: api/nn/LayerNormalization.md
      Linear: api/nn/Linear.md
      MaxPool: api/nn/MaxPool.md
      Reshape: api/nn/Reshape.md
      Sequential: api/nn/Sequential.md
      sequential: api/nn/sequential.md
    regularizers:
      GlobalL1: api/regularizers/GlobalL1.md
      GlobalL1L2: api/regularizers/GlobalL1L2.md
      GlobalL2: api/regularizers/GlobalL2.md
    to_module: api/to_module.md
extra:
  search:
    language: en
  social:
  - icon: octicons/mark-github-16
    link: https://github.com/cgarciae
  - icon: octicons/mark-github-16
    link: https://github.com/charlielito
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cgarciae88
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/cgarciae
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/calvarez92
markdown_extensions:
- admonition
- codehilite
- pymdownx.arithmatex
plugins:
- search
- mkdocstrings
- mkdocs-jupyter
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
