site_name: Elegy
repo_name: poets-ai/elegy
repo_url: https://github.com/poets-ai/elegy
site_url: https://poets-ai.github.io/elegy

theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16

nav:
  - Introduction: index.md
  - Getting Started: getting-started.ipynb
  - Guides:
      The Module System: guides/module-system.md
      Modules, Losses, and Metrics: guides/modules-losses-metrics.md
      Contibuting: guides/contributing.md
  - API Reference:
      module:
        Module: api/module/Module.md
      model:
        Model: api/model/Model.md
        load: api/model/load.md
      nn:
        Linear: api/nn/Linear.md
        Conv2D: api/nn/Conv2D.md
        Flatten: api/nn/Flatten.md
        BatchNormalization: api/nn/BatchNormalization.md
        Dropout: api/nn/Dropout.md
      metrics:
        Metric: api/metrics/Metric.md
        Accuracy: api/metrics/Accuracy.md
        BinaryCrossentropy: api/metrics/BinaryCrossentropy.md
        CategoricalAccuracy: api/metrics/CategoricalAccuracy.md
        SparseCategoricalAccuracy: api/metrics/SparseCategoricalAccuracy.md
        Mean: api/metrics/Mean.md
        MeanAbsoluteError: api/metrics/MeanAbsoluteError.md
        MeanSquaredError: api/metrics/MeanSquaredError.md
      losses:
        Loss: api/losses/Loss.md
        BinaryCrossentropy: api/losses/BinaryCrossentropy.md
        CategoricalCrossentropy: api/losses/CategoricalCrossentropy.md
        SparseCategoricalCrossentropy: api/losses/SparseCategoricalCrossentropy.md
        MeanAbsoluteError: api/losses/MeanAbsoluteError.md
        MeanSquaredError: api/losses/MeanSquaredError.md
        mean_squared_error: api/losses/mean_squared_error.md
      regularizers:
        GlobalL1: api/regularizers/GlobalL1.md
        GlobalL2: api/regularizers/GlobalL2.md
        GlobalL1L2: api/regularizers/GlobalL1L2.md
      callbacks:
        Callback: api/callbacks/Callback.md
        ModelCheckpoint: api/callbacks/ModelCheckpoint.md
        EarlyStopping: api/callbacks/EarlyStopping.md
        LambdaCallback: api/callbacks/LambdaCallback.md
        CSVLogger: api/callbacks/CSVLogger.md
        RemoteMonitor: api/callbacks/RemoteMonitor.md
        TerminateOnNaN: api/callbacks/TerminateOnNaN.md
        Tensorboard: api/callbacks/TensorBoard.md

extra:
  search:
    language: en
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/cgarciae
    - icon: octicons/mark-github-16
      link: https://github.com/charlielito
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cgarciae88
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cgarciae
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/calvarez92

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
