site_name: Elegy
repo_name: poets-ai/elegy
repo_url: https://github.com/poets-ai/elegy
site_url: https://poets-ai.github.io/elegy

theme:
  name: material
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16

nav:
  - Introduction: index.md
  - API Reference:
      metrics:
        Accuracy: api/metrics/accuracy.md
        MeanMetricsWrapper: api/metrics/mean_metrics_wrapper.md

extra:
  search:
    language: en
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/cgarciae
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cgarciae88
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cgarciae

markdown_extensions:
  - admonition
  - codehilite

plugins:
  - search
  - mkdocstrings
